pull_request_rules:
  - name: automatic merge on review
    conditions:
      - "#approved-reviews-by>=0"
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge